// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMv2GGRf1XanthtfDmurphqsrzhU6PgOU',
    appId: '1:96918783298:web:3378a187b1964b54e5b4db',
    messagingSenderId: '96918783298',
    projectId: 'planify-app-e6a0d',
    authDomain: 'planify-app-e6a0d.firebaseapp.com',
    storageBucket: 'planify-app-e6a0d.appspot.com',
    measurementId: 'G-7VJN1QL7CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMhd1rngLvtMUxrC0p3aHmwrXiLQRjwlc',
    appId: '1:96918783298:android:6cf77e06f1d1889be5b4db',
    messagingSenderId: '96918783298',
    projectId: 'planify-app-e6a0d',
    storageBucket: 'planify-app-e6a0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt5oQ4yV4-8ArQQDtONjqpgskbo08lsgY',
    appId: '1:96918783298:ios:8363baa553ec3a37e5b4db',
    messagingSenderId: '96918783298',
    projectId: 'planify-app-e6a0d',
    storageBucket: 'planify-app-e6a0d.appspot.com',
    iosClientId: '96918783298-i4v9788ju3t1dfn1cetud8sai6gvlgv9.apps.googleusercontent.com',
    iosBundleId: 'capital.rezia.planify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt5oQ4yV4-8ArQQDtONjqpgskbo08lsgY',
    appId: '1:96918783298:ios:c1df4139399fe5bce5b4db',
    messagingSenderId: '96918783298',
    projectId: 'planify-app-e6a0d',
    storageBucket: 'planify-app-e6a0d.appspot.com',
    iosClientId: '96918783298-8gjaom1acpr1e861r33up2486boptdh9.apps.googleusercontent.com',
    iosBundleId: 'com.erizzarate.planify',
  );
}
