// Created by Tayyab Mughal on 19/02/2023.
// Tayyab Mughal
// tayyabmughal676@gmail.com
// © 2022-2023  - All Rights Reserved

import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';
import 'package:planify/app_resources/app_resources.dart';

import 'get_generic_text_widget.dart';

class TripCounterContainer extends StatelessWidget {
  final String counter;
  final String numberOfUsers;

  const TripCounterContainer({
    super.key,
    required this.counter,
    required this.numberOfUsers,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      height: sizes!.heightRatio * 180,
      width: sizes!.widthRatio * 360,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(14),
        boxShadow: const [
          BoxShadow(
            color: AppColors.mainBlack100,
            spreadRadius: 0,
            blurRadius: 0,
            offset: Offset(-7, 7), // changes position of shadow
          ),
        ],
        gradient: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            AppColors.counterGradientColorOne,
            AppColors.counterGradientColorTwo
          ],
        ),
      ),
      child: Stack(
        alignment: Alignment.topCenter,
        children: [
          //TODO: Need to recheck
          Positioned(
            top: 0,
            bottom: 0,
            right: 0,
            left: 0,
            child: Padding(
              padding: EdgeInsets.symmetric(horizontal: sizes!.widthRatio * 12),
              child: Lottie.asset(
                'assets/json/heart_animation.json',
                height: sizes!.heightRatio * 100,
                width: sizes!.widthRatio * 300,
                fit: BoxFit.fill,
              ),
            ),
          ),
          Positioned(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                GetGenericText(
                  text: counter,
                  fontFamily: Assets.basement,
                  fontSize: 60,
                  fontWeight: FontWeight.w800,
                  color: AppColors.mainBlack200,
                  lines: 1,
                ),
                CommonPadding.sizeBoxWithHeight(height: 12),
                GetGenericText(
                  text: "Trips Generated by $numberOfUsers users",
                  fontFamily: Assets.aileron,
                  fontSize: 20,
                  fontWeight: FontWeight.w400,
                  color: AppColors.mainBlack100,
                  lines: 1,
                )
              ],
            ),
          ),
        ],
      ),
    );
  }
}
